#!/bin/bash

# Устанавливаем ваш пакет
pip install -e .

# Устанавливаем PyTorch (CPU)
pip install torch==2.5.1+cpu \
  --index-url https://download.pytorch.org/whl/cpu

# Устанавливаем PyG и экстеншны
pip install torch_scatter==2.1.2+pt25cpu \
  --find-links https://data.pyg.org/whl/torch-2.5.1+cpu.html

pip install torch_sparse==0.6.18+pt25cpu \
  --find-links https://data.pyg.org/whl/torch-2.5.1+cpu.html

pip install torch_cluster==1.6.3+pt25cpu \
  --find-links https://data.pyg.org/whl/torch-2.5.1+cpu.html

pip install torch_spline_conv==1.2.2+pt25cpu \
  --find-links https://data.pyg.org/whl/torch-2.5.1+cpu.html

pip install torch_geometric==2.5.3 \
  --find-links https://data.pyg.org/whl/torch-2.5.1+cpu.html
